import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.54.0';
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'apikey, x-client-info, content-type, authorization',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
};
serve(async (req)=>{
  console.log('🚀 Drelf Public Payment Edge Function started');
  if (req.method === 'OPTIONS') {
    return new Response('ok', {
      headers: corsHeaders
    });
  }
  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Missing Supabase environment variables');
    }
    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const body = await req.json();
    console.log('✅ Received body for Drelf payment:', JSON.stringify(body));
    const { subscriptionType, paymentMethod, userName, userEmail, phoneNumber, address, amount, quantity } = body;
    const physicalProducts = [
      'drelf',
      'fitfactor',
      'hungrylater',
      'parfum',
      'jewelry',
      'dev',
      'ebook_diet'
    ];
    // Base validation for all products
    const baseRequired = {
      subscriptionType,
      paymentMethod,
      userName,
      userEmail,
      phoneNumber,
      amount,
      quantity
    };
    for (const [key, value] of Object.entries(baseRequired)){
      if (!value && value !== 0) {
        return new Response(JSON.stringify({
          error: `Missing required field in request body: ${key}`
        }), {
          status: 400,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json'
          }
        });
      }
    }
    // Additional validation for physical products
    if (physicalProducts.includes(subscriptionType) && subscriptionType !== 'dev' && subscriptionType !== 'ebook_diet' && !address) {
      return new Response(JSON.stringify({
        error: 'Missing required field for physical product: address'
      }), {
        status: 400,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        }
      });
    }
    // merchant_ref is now generated by frontend, but we'll re-generate if not present for robustness
    let merchant_ref = body.merchant_ref || 'EVG_' + Date.now().toString() + '_' + subscriptionType;
    const ipAddress = req.headers.get('x-forwarded-for') ?? req.headers.get('remote-addr');
    let vpsResult; // Declare vpsResult here to be accessible later                                                                                                              
    const productMap = {
      'drelf': 'Drelf Collagen',
      'fitfactor': 'Fitfactor',
      'hungrylater': 'Hungrylater',
      'parfum': 'Parfum',
      'dev': 'Dev',
      'jewelry': 'Jewelry',
      'ebook_diet': 'Ebook_diet'
    };
    const productName = body.productName || productMap[subscriptionType] || subscriptionType;
    // --- NEW LOGIC FOR PHYSICAL PRODUCTS ---                                                                                                                                   
    if (physicalProducts.includes(subscriptionType)) {
      console.log(`Detected physical product: ${subscriptionType}. Handling global_product insertion.`);
      // 1. Insert initial UNPAID record into global_product                                                                                                                     
      const { data: globalProductInsertData, error: globalProductInsertError } = await supabase.from('global_product').insert({
        name: userName,
        phone: phoneNumber,
        email: userEmail,
        address: address,
        product_name: productName,
        amount: amount,
        status: 'UNPAID',
        merchant_ref: merchant_ref
      }).select('id').single();
      if (globalProductInsertError) {
        console.error('❌ Database insert error into global_product:', globalProductInsertError.message);
        return new Response(JSON.stringify({
          success: false,
          error: 'Failed to create initial product record',
          details: globalProductInsertError.message
        }), {
          status: 500,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json'
          }
        });
      }
      const insertedGlobalProductId = globalProductInsertData.id;
      console.log(`✅ Inserted into global_product with ID: ${insertedGlobalProductId}`);
      // 2. Call PHP proxy (TriPay)
      const vpsUrl = "https://payment.elvisiongroup.com/create-payment";
      const vpsPayload = {
        subscriptionType: subscriptionType,
        paymentMethod: paymentMethod,
        userName: userName,
        userEmail: userEmail,
        phoneNumber: phoneNumber,
        address: address,
        quantity: quantity,
        amount: amount,
        merchant_ref: merchant_ref,
        productName: productName
      };
      console.log('📤 VPS Payload (physical product):', JSON.stringify(vpsPayload));
      const vpsResponse = await fetch(vpsUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(vpsPayload)
      });
      const responseText = await vpsResponse.text();
      console.log('📄 FULL VPS Response text (physical product):', responseText);
      if (!vpsResponse.ok) {
        console.error('💥 VPS Error detected (physical product):', vpsResponse.status, responseText); // Rollback: Delete the global_product record if TriPay call fails
        await supabase.from('global_product').delete().eq('id', insertedGlobalProductId);
        return new Response(JSON.stringify({
          success: false,
          error: 'Payment service error',
          message: `The external payment service returned an error: ${responseText}`
        }), {
          status: vpsResponse.status,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json'
          }
        });
      }
      try {
        vpsResult = JSON.parse(responseText);
      } catch (parseError) {
        console.error('⚠️ JSON parse failed (drelf):', parseError.message);
        await supabase.from('global_product').delete().eq('id', insertedGlobalProductId);
        return new Response(JSON.stringify({
          error: 'Invalid VPS response format',
          message: 'Payment service returned non-JSON data.'
        }), {
          status: 502,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json'
          }
        });
      }
      console.log('✅ Parsed VPS response successfully (drelf)');
      // 3. Update global_product with TriPay reference
      if (vpsResult?.success && vpsResult.reference) {
        const { error: updateGlobalProductError } = await supabase.from('global_product').update({
          tripay_reference: vpsResult.reference
        }).eq('id', insertedGlobalProductId);
        if (updateGlobalProductError) {
          console.error('❌ Error updating global_product with tripay_reference:', updateGlobalProductError.message);
          // This is a critical error, but might not prevent frontend display of payment instructions
          vpsResult.warning = 'Failed to update global_product with TriPay reference.';
        } else {
          console.log(`✅ Updated global_product ID ${insertedGlobalProductId} with TriPay reference: ${vpsResult.reference}`);
        }
      } else {
        console.warn('⚠️ TriPay call was successful, but no reference returned. Not updating global_product.');
      }
      // Return the TriPay result to the frontend
      return new Response(JSON.stringify(vpsResult), {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        },
        status: 200
      });
    }
   } catch (error) {
    console.error('💥💥💥 PUBLIC PAYMENT EDGE FUNCTION CRASH 💥💥💥');
    console.error('💥 Edge Function error:', error.message);
    console.error('💥 Error stack:', error.stack);
    return new Response(JSON.stringify({
      error: 'Internal server error',
      message: error.message
    }), {
      status: 500,
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/json'
      }
    });
  }
});
