-- Schema for Sileme ("Absen Hidup") Feature

-- 1. Create the table to track user check-ins and their contacts.
-- This table will store the user's ID, their last check-in time, and their emergency contacts.
CREATE TABLE public.absen_hidup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    last_checked_in TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    contacts JSONB, -- Store up to 3 contacts: [{name, email, phone}, ...]
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

-- RLS (Row Level Security) Policies
-- Users should only be able to manage their own "absen_hidup" record.
ALTER TABLE public.absen_hidup ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage their own absen_hidup record"
ON public.absen_hidup
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 2. Create the Supabase Edge Function to handle alerts.
-- This is a placeholder for the function you would create at:
-- supabase/functions/sent-absen-alert/index.ts

/*
// Supabase Edge Function: supabase/functions/sent-absen-alert/index.ts
// This function would be triggered by a cron job.

import { createClient } from '@supabase/supabase-js';

// WARNING: Use environment variables for Supabase URL and Anon Key in a real project.
// const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_ANON_KEY')!);

Deno.serve(async (req) => {
  try {
    // 1. Find users who haven't checked in for 48 hours.
    const fortyEightHoursAgo = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();

    const { data: overdueUsers, error } = await supabase
      .from('absen_hidup')
      .select('user_id, contacts')
      .lt('last_checked_in', fortyEightHoursAgo);

    if (error) throw error;

    // 2. For each overdue user, send alerts to their contacts.
    for (const user of overdueUsers) {
      const contacts = user.contacts; // Assuming contacts is [{name, email, phone}, ...]

      if (contacts && Array.isArray(contacts)) {
        for (const contact of contacts) {
          console.log(`Sending alert for user ${user.user_id} to ${contact.name} at ${contact.email} / ${contact.phone}`);
          // Add your email/SMS sending logic here (e.g., using Twilio, SendGrid).
          // Example:
          // await sendEmail({ to: contact.email, subject: 'Wellness Check Alert', body: '...' });
          // await sendSms({ to: contact.phone, body: 'Wellness Check Alert for...' });
        }
      }
    }

    return new Response(JSON.stringify({ message: `Checked ${overdueUsers.length} users.` }), {
      headers: { 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (err) {
    return new Response(String(err?.message ?? err), { status: 500 });
  }
});

-- 3. Schedule the function with a cron job.
-- Use the pg_cron extension in Supabase to run the check daily.
-- This command schedules the job to run once every hour.
SELECT cron.schedule(
    'check-absen-hidup',
    '0 * * * *', -- Run every hour
    $$
    SELECT net.http_post(
        url:='https://<YOUR_PROJECT_REF>.supabase.co/functions/v1/sent-absen-alert',
        headers:='{"Authorization": "Bearer <YOUR_SUPABASE_ANON_KEY>"}'
    )
    $$
);

*/
