import React, { useState, useEffect } from 'react';
import { Heart, Shield, ArrowRight, Clock, Check, X, AlertCircle, Sparkles, User, Mail, Phone, CreditCard, Copy } from 'lucide-react';
import { FaWhatsapp } from 'react-icons/fa';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Toaster } from '@/components/ui/toaster';
import { 
  initFacebookPixelWithLogging, 
  trackPageViewEvent, 
  trackViewContentEvent,
  trackAddPaymentInfoEvent,
  trackPurchaseEvent, 
  getFbcFbpCookies,
  AdvancedMatchingData,
  waitForFbp
} from '@/utils/fbpixel';

const ArifEbookLanding = () => {
  const [timeLeft, setTimeLeft] = useState({ hours: 11, minutes: 47, seconds: 23 });
  const [userName, setUserName] = useState('');
  const [userEmail, setUserEmail] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [selectedPaymentMethod, setSelectedPaymentMethod] = useState('QRIS');
  const [showPaymentInstructions, setShowPaymentInstructions] = useState(false);
  const [loading, setLoading] = useState(false);
  const [paymentData, setPaymentData] = useState<any>(null);

  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const affiliateRef = searchParams.get('ref');
  const { toast } = useToast();
  const { user } = useAuth();

  const productNameBackend = 'ebook_elvision';
  const displayProductName = 'Ebook Rahasia Kesembuhan Natural';
  const productPrice = 200000;
  const totalQuantity = 1;
  const totalAmount = productPrice;
  const pixelId = '3319324491540889'; // Using EbookIndo Pixel ID

  useEffect(() => {
    if (typeof window !== 'undefined') {
      initFacebookPixelWithLogging(pixelId);
      
      const pageEventId = `pageview-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
      trackPageViewEvent({}, pageEventId, pixelId);
      sendCapiEvent('PageView', {}, pageEventId);

      const viewContentEventId = `viewcontent-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
      trackViewContentEvent({
        content_name: displayProductName,
        content_ids: [productNameBackend],
        content_type: 'product',
        value: totalAmount,
        currency: 'IDR'
      }, viewContentEventId, pixelId);
      
      sendCapiEvent('ViewContent', {
        content_name: displayProductName,
        content_ids: [productNameBackend],
        content_type: 'product',
        value: totalAmount,
        currency: 'IDR'
      }, viewContentEventId);
    }

    const timer = setInterval(() => {
      setTimeLeft(prev => {
        if (prev.seconds > 0) return { ...prev, seconds: prev.seconds - 1 };
        else if (prev.minutes > 0) return { ...prev, minutes: prev.minutes - 1, seconds: 59 };
        else if (prev.hours > 0) return { hours: prev.hours - 1, minutes: 59, seconds: 59 };
        return prev;
      });
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const scrollToCheckout = () => {
    document.getElementById('checkout')?.scrollIntoView({ behavior: 'smooth' });
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0,
    }).format(amount);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Berhasil Disalin",
      description: "Teks telah disalin ke clipboard",
    });
  };

  const sendCapiEvent = async (eventName: string, eventData: any, eventId?: string) => {
    try {
      // ⏳ Wait for FBP to be generated by browser pixel
      await waitForFbp();

      const { data: { session } } = await supabase.auth.getSession();
      const body: any = {
        pixelId: '3319324491540889',
        eventName,
        customData: eventData,
        eventId: eventId,
        eventSourceUrl: window.location.href,
      };

      // Get FBC and FBP from cookies using the utility function
      const { fbc, fbp } = getFbcFbpCookies();

      const userData: any = {
        client_user_agent: navigator.userAgent,
      };

      // Prioritize form input email/phone, then authenticated user email/phone
      if (userEmail) {
        userData.email = userEmail;
      } else if (session?.user?.email) {
        userData.email = session.user.email;
      }
      if (phoneNumber) {
        userData.phone = phoneNumber;
      } else if (session?.user?.user_metadata?.phone) {
        userData.phone = session.user.user_metadata.phone;
      }

      // External ID from authenticated user (Supabase user ID)
      if (session?.user?.id) {
        userData.external_id = session.user.id;
      } else if (user?.id) { // Fallback if session is not available but user from useAuth is
        userData.external_id = user.id;
      }

      if (fbc) {
        userData.fbc = fbc;
      }
      if (fbp) {
        userData.fbp = fbp;
      }
      
      body.userData = userData;

      await supabase.functions.invoke('capi-universal', { body });
    } catch (err) {
      console.error('Failed to send CAPI event:', err);
    }
  };

  useEffect(() => {
    if (!showPaymentInstructions || !paymentData?.tripay_reference) return;
    
    const channel = supabase
      .channel(`payment-${paymentData.tripay_reference}`)
      .on('postgres_changes', { 
        event: 'UPDATE', 
        schema: 'public', 
        table: 'global_product', 
        filter: `tripay_reference=eq.${paymentData.tripay_reference}`
      }, (payload) => {
        if (payload.new?.status === 'PAID') {
          toast({
              title: "LUNAS! Akses Dikirim.",
              description: "Pembayaran berhasil. Cek email Anda sekarang untuk akses Audio & Ebook.",
              duration: 5000, 
              variant: "default"
          });

          // Track Client-Side Purchase Event
          const eventId = paymentData.tripay_reference;
          const purchaseUserData: AdvancedMatchingData = {
            em: userEmail,
            ph: phoneNumber,
            fn: userName,
            external_id: user?.id
          };

          trackPurchaseEvent({
            content_name: displayProductName,
            content_ids: [productNameBackend],
            content_type: 'product',
            value: totalAmount,
            currency: 'IDR',
            transaction_id: eventId
          }, eventId, pixelId, purchaseUserData);

          // FIRST-WIN DEDUPLICATION CHECK
          const isBackendCapiSent = payload.new?.capi_purchase_sent === true;

          if (isBackendCapiSent) {
             console.log(`⏭️ CAPI Purchase Skipped (Backend already sent)`);
          } else {
             // Send CAPI Purchase (Frontend wins)
             sendCapiEvent('Purchase', {
               content_ids: [productNameBackend],
               content_type: 'product',
               value: totalAmount,
               currency: 'IDR'
             }, eventId);
          }

          // Optional: redirect to a thank you page or just show success state
        }
      }).subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [showPaymentInstructions, paymentData]);

  useEffect(() => {
    if (user) {
      setUserName(user.user_metadata?.full_name || '');
      setUserEmail(user.email || '');
      setPhoneNumber(user.user_metadata?.phone || '');
    }
  }, [user]);

  const handleCreatePayment = async () => {
    if (!userName || !userEmail || !phoneNumber || !selectedPaymentMethod) {
      toast({
        title: "Data Tidak Lengkap",
        description: "Mohon lengkapi nama, email, no. whatsapp, dan metode pembayaran.",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);

    const addPaymentInfoEventId = `addpaymentinfo-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
    const userDataPixel: AdvancedMatchingData = {
      em: userEmail,
      ph: phoneNumber,
      fn: userName,
      external_id: user?.id
    };

    // Track AddPaymentInfo
    trackAddPaymentInfoEvent({
      content_ids: [productNameBackend],
      content_type: 'product',
      value: totalAmount,
      currency: 'IDR'
    }, addPaymentInfoEventId, pixelId, userDataPixel);
    
    sendCapiEvent('AddPaymentInfo', {
      content_ids: [productNameBackend],
      content_type: 'product',
      value: totalAmount,
      currency: 'IDR'
    }, addPaymentInfoEventId);

    const currentUserId = user?.id;
    const { fbc, fbp } = getFbcFbpCookies();

    try {
      const payload: any = {
        subscriptionType: productNameBackend,
        paymentMethod: selectedPaymentMethod,
        userName: userName,
        userEmail: userEmail,
        phoneNumber: phoneNumber,
        amount: totalAmount,
        quantity: totalQuantity,
        productName: displayProductName,
        affiliateRef: affiliateRef,
        fbc,
        fbp
      };

      if (currentUserId) {
        payload.userId = currentUserId;
      }

      const { data, error } = await supabase.functions.invoke('tripay-create-payment', {
        body: payload
      });

      if (error || !data?.success) {
        toast({
          title: "Gagal Memproses",
          description: data?.error || error?.message || "Terjadi kesalahan sistem.",
          variant: "destructive",
        });
        setLoading(false); // Make sure to stop loading on failure
        return;
      }

      if (data?.success) {
        setPaymentData(data);
        setShowPaymentInstructions(true);
        toast({
          title: "Order Dibuat!",
          description: "Silakan selesaikan pembayaran Anda.",
        });
        window.scrollTo({ top: 0, behavior: 'smooth' });
      }
    } catch (error: any) {
      console.error('Payment Error:', error);
      toast({
        title: "Error",
        description: "Gagal menghubungi server pembayaran.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const paymentMethods = [
    { code: 'QRIS', name: 'QRIS', description: 'Scan pakai GoPay, OVO, Dana, ShopeePay' },
    { code: 'BCAVA', name: 'BCA Virtual Account', description: 'Transfer via BCA' },
    { code: 'BNIVA', name: 'BNI Virtual Account', description: 'Transfer via BNI' },
    { code: 'BRIVA', name: 'BRI Virtual Account', description: 'Transfer via BRI' },
  ];

  if (showPaymentInstructions && paymentData) {
    return (
      <div className="min-h-screen bg-black pb-20 font-sans text-white">
        <Toaster />
        <div className="max-w-md mx-auto bg-gray-900 min-h-screen shadow-2xl border-x border-gray-800">
          <div className="p-4 bg-red-600 text-white flex items-center gap-2 sticky top-0 z-10">
            <button onClick={() => setShowPaymentInstructions(false)} className="text-white hover:bg-red-700 p-2 rounded-full">
              <X className="w-6 h-6" />
            </button>
            <h1 className="font-bold text-lg">Selesaikan Pembayaran</h1>
          </div>

          <div className="p-6 space-y-6">
            <div className="text-center">
                <p className="text-gray-400">Total Tagihan</p>
                <p className="text-4xl font-bold text-green-500">{formatCurrency(paymentData.amount)}</p>
                <div className="mt-2 inline-block px-3 py-1 bg-red-900/30 text-red-400 rounded-full text-sm font-medium border border-red-500/30">
                    Menunggu Pembayaran
                </div>
            </div>

            <div className="bg-gray-800 border-gray-700 border-2 rounded-lg p-6 space-y-4">
                {paymentData.qrUrl && (
                    <div className="flex flex-col items-center">
                        <img src={paymentData.qrUrl} alt="QRIS" className="w-64 h-64 object-contain bg-white p-2 rounded-lg" />
                        <p className="text-sm text-gray-400 mt-4 text-center">Scan QR di atas menggunakan aplikasi e-wallet atau mobile banking Anda.</p>
                    </div>
                )}
                
                {paymentData.payCode && (
                    <div className="space-y-2">
                        <label className="text-gray-300">Kode Bayar / Virtual Account</label>
                        <div className="flex items-center justify-between bg-black p-3 rounded-lg border border-gray-700">
                            <span className="font-mono text-xl font-bold tracking-wider text-yellow-400">{paymentData.payCode}</span>
                            <button onClick={() => copyToClipboard(paymentData.payCode)} className="text-gray-400 hover:text-white p-2 rounded-full">
                                <Copy className="w-4 h-4" />
                            </button>
                        </div>
                    </div>
                )}

                <div className="bg-red-900/20 p-3 rounded text-sm text-red-300 border border-red-900/50">
                    <p><strong>PENTING:</strong> Lakukan pembayaran sebelum waktu habis. Sistem akan otomatis memverifikasi pembayaran Anda dalam 1-2 menit.</p>
                </div>
              </div>
            
            <div className="text-center">
               <p className="text-sm text-gray-500 mb-4">Sudah bayar tapi status belum berubah?</p>
               <button className="w-full flex items-center justify-center gap-2 border border-green-600 text-green-500 hover:bg-green-600 hover:text-white p-3 rounded-lg" onClick={() => window.open(`https://wa.me/62895325633487?text=Halo admin, saya sudah bayar untuk order ${paymentData.tripay_reference} tapi belum aktif.`, '_blank')}>
                   <FaWhatsapp /> Hubungi Bantuan Admin
               </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <Toaster />
      {/* Hero Section - Pain Point */}
      <section className="relative min-h-screen flex items-center justify-center px-4 py-20 bg-gradient-to-b from-gray-900 to-black">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <div className="inline-block bg-red-600 px-6 py-2 rounded-full text-sm font-bold animate-pulse mb-4">
            ⚠️ PROMO BERAKHIR {timeLeft.hours}:{String(timeLeft.minutes).padStart(2,'0')}:{String(timeLeft.seconds).padStart(2,'0')}
          </div>
        
          <h1 className="text-4xl md:text-6xl font-bold leading-tight">
            Anda Sudah Menghabiskan <span className="text-red-500">Puluhan Juta</span> untuk Kesehatan...
          </h1>
        
          <p className="text-2xl md:text-3xl text-gray-300">
            Tapi Kondisi <span className="text-red-400 font-bold">Tidak Membaik</span>?
          </p>
        
          <div className="bg-gray-800 border-2 border-red-500 rounded-xl p-8 my-8">
            <p className="text-xl leading-relaxed text-gray-200">
              Saya <span className="text-yellow-400 font-bold">Syarifudin Arif</span>. Maret 2023, dokter memberi saya vonis: <span className="text-red-400 font-bold">Kanker Otak Stadium 4</span>. Estimasi hidup saya: <span className="text-red-300">7-18 bulan</span>.
            </p>
            <p className="text-2xl font-bold text-green-400 mt-6">
              Hari ini, Desember 2025, saya masih di sini—SEHAT dan KUAT.
            </p>
          </div>
        
          <div className="bg-red-900/20 border-2 border-red-600 rounded-xl p-6">
            <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
            <p className="text-lg font-semibold text-red-300 mb-3">SAYA AKAN JUJUR DENGAN ANDA:</p>
            <p className="text-gray-200 leading-relaxed">
              Saya akan jujur. Saya ingin mendedikasikan diri setelah terbantu oleh program eL Vision ini untuk menolong yang lain.
            </p>
            <p className="text-gray-200 leading-relaxed">
              Tapi lebih dari itu, saya ingin memberikan harapan—seperti yang diberikan kepada saya.
            </p>
            <p className="text-yellow-400 font-bold mt-4">
              Saya akan Jujur, Bahwa saya tertolong setelah mengikuti eL Vision ini, dari no Hope menjadi terang, tenang, damai sungguh penuh ketenangan, dan saya sudah bernazar akan membantu orang mendedikasikan diri membantu orang orang di titik gelap sebagai mana saya dulu melalui eL Vision ini, ini adalah Movement, bahwa harapan selalu ada, bahwa kekuatan kedamaian bekerja melampaui pengetahuan yang terbatas saat ini.
            </p>
          </div>
        
          <button 
            onClick={scrollToCheckout}
            className="bg-gradient-to-r from-green-500 to-emerald-600 text-white text-xl md:text-2xl font-bold py-6 px-12 rounded-full hover:from-green-600 hover:to-emerald-700 transition-all transform hover:scale-105 shadow-2xl inline-flex items-center gap-3 animate-pulse"
          >
            Saya Ingin Sehat Seperti Arif <ArrowRight className="w-6 h-6" />
          </button>
        </div>
      </section>

      {/* Health Section - Arif's Story */}
      <div className="py-20 bg-gradient-to-b from-gray-900 to-black">
        <div className="container mx-auto px-6">
          <div className="max-w-5xl mx-auto">
            <div className="text-center mb-12">
              <div className="inline-block bg-gradient-to-r from-green-500/20 to-emerald-500/20 border border-green-500/30 rounded-full px-6 py-2 mb-4">
                <span className="text-green-400 font-bold">TRANSFORMASI KESEHATAN</span>
              </div>
              <h2 className="text-5xl font-bold mb-6">
                <span className="bg-gradient-to-r from-green-400 to-emerald-400 bg-clip-text text-transparent">
                  Ketika Medis Memberikan Vonis, Alam Memberikan Jalan Lain
                </span>
              </h2>
            </div>

            {/* Arif's Video Testimonials */}
            <div className="bg-gradient-to-br from-gray-900 to-black border-2 border-green-500/50 rounded-2xl p-10 mb-8">
              <div className="flex items-center gap-4 mb-6">
                <div className="text-5xl">🏥</div>
                <div className="flex-1">
                  <h3 className="text-3xl font-bold text-green-400">Syarifudin Arif</h3>
                  <p className="text-lg text-gray-400">Instagram: @syarifudin_arif25</p>
                  <p className="text-sm text-gray-500 mt-1">Penyintas Kanker Otak Stadium 4</p>
                </div>
              </div>
              
              <div className="mb-8 max-w-sm mx-auto">
                <video 
                  className="w-full rounded-lg shadow-xl border border-gray-800"
                  controls
                  preload="metadata"
                  playsInline
                  webkit-playsinline="true"
                  poster="https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/arifweb/arif2.jpeg"
                >
                  <source src="https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/arifweb/arif2.mp4" type="video/mp4" />
                  Browser Anda tidak mendukung pemutaran video.
                </video>
              </div>

              {/* Additional Testimonial Images */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                {[3, 4, 5, 6].map((num) => (
                  <img 
                    key={num}
                    src={`https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/arifweb/arif${num}.jpeg`}
                    alt={`Testimonial ${num}`}
                    className="w-full h-auto rounded-lg shadow-md border border-gray-800 hover:scale-105 transition-transform cursor-pointer"
                  />
                ))}
              </div>

              <div className="bg-gradient-to-r from-red-900/30 to-green-900/30 border border-green-500/30 rounded-xl p-6 mb-6">
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <div className="text-red-400 font-bold text-lg mb-2">📋 Vonis Medis - Maret 2023</div>
                    <p className="text-gray-300">Kanker Otak Stadium 4</p>
                    <p className="text-gray-300">Estimasi Waktu: 7-18 Bulan</p>
                  </div>
                  <div>
                    <div className="text-green-400 font-bold text-lg mb-2">✨ Realitas - Desember 2025</div>
                    <p className="text-gray-300">Masih Hidup & Sehat</p>
                    <p className="text-gray-300">Kondisi Semakin Membaik</p>
                  </div>
                </div>
              </div>

              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p className="text-xl font-semibold text-white">
                  Bagaimana eL Vision Membantu Transformasi Kesehatan Pak Arif?
                </p>
                
                <p>
                  Perlu diketahui, vonis awal kanker stadium akhir telah diterima sejak Maret 2023, dengan estimasi medis bertahan hidup antara 7 hingga 18 bulan sejak vonis tersebut.  <span className="text-green-400 font-semibold">tubuh manusia memiliki kemampuan penyembuhan alami yang luar biasa</span> - yang sering kali terblokir oleh kondisi mental dan emosional.
                </p>

                <div className="bg-gradient-to-r from-green-900/20 to-emerald-900/20 border border-green-500/30 rounded-lg p-6 my-4">
                  <h4 className="text-xl font-bold text-green-400 mb-3">🧠 Metode Custom Terapi Frekuensi eL Vision</h4>
                  <p className="mb-3">
                    Kami bekerja pada level <span className="text-green-400 font-semibold">alam bawah sadar untuk menetralkan sel-sel abnormal</span>. Meski terdengar mustahil bagi pendekatan medis konvensional, prinsip ini sebenarnya sudah diakui dalam bidang psychoneuroimmunology - ilmu yang mempelajari hubungan antara pikiran, sistem saraf, dan sistem kekebalan tubuh.
                  </p>
                  
                  <div className="space-y-2 ml-4">
                    <p className="flex items-start gap-2">
                      <span className="text-green-400 mt-1">•</span>
                      <span><strong>Kalibrasi Alam Bawah Sadar:</strong> Kami memprogram ulang respons otomatis tubuh terhadap sel abnormal, mengaktifkan mekanisme penyembuhan alami yang selama ini tertidur</span>
                    </p>
                    <p className="flex items-start gap-2">
                      <span className="text-green-400 mt-1">•</span>
                      <span><strong>Terapi Frekuensi Spesifik:</strong> Setiap sel memiliki frekuensi getaran. Kami membantu menyelaraskan frekuensi tubuh ke kondisi optimal untuk regenerasi</span>
                    </p>
                    <p className="flex items-start gap-2">
                      <span className="text-green-400 mt-1">•</span>
                      <span><strong>Water Fasting Protocol:</strong> Dikombinasikan dengan protokol puasa air yang terbukti memicu autophagy - proses alami tubuh membersihkan sel-sel rusak</span>
                    </p>
                    <p className="flex items-start gap-2">
                      <span className="text-green-400 mt-1">•</span>
                      <span><strong>Stress Neutralization:</strong> Menghilangkan stres kronis yang menekan sistem imun, membiarkan tubuh fokus pada penyembuhan</span>
                    </p>
                  </div>
                </div>

                <p className="text-lg text-yellow-400 font-semibold italic">
                  "Sains medis mengukur probabilitas, tetapi tidak memiliki otoritas penuh atas kehidupan. Alam, ketika dipahami dan diselaraskan dengan benar, jauh lebih penuh belas kasih dari yang dibayangkan."
                </p>

                <p>
                  Hasil Pak Arif bukan keajaiban dalam artian supernatural - ini adalah <span className="text-green-400 font-semibold">hasil dari mengaktifkan kembali sistem penyembuhan alami tubuh yang sudah ada sejak lahir</span>, namun sering terblokir oleh pola pikir, emosi negatif, dan stres berkepanjangan.
                </p>

                <div className="bg-amber-900/20 border border-amber-500/30 rounded-lg p-4 mt-4">
                  <p className="text-amber-400 text-sm">
                    <strong>Disclaimer:</strong> Metode eL Vision bukan pengganti pengobatan medis. Kami bekerja sebagai pendamping yang mengoptimalkan kondisi mental-emosional untuk mendukung proses penyembuhan alami tubuh. Konsultasikan dengan dokter Anda untuk keputusan medis.
                  </p>
                </div>
              </div>
            </div>

            <div className="text-center">
              <p className="text-2xl text-gray-300 italic">
                "Tubuh Anda lebih kuat dari diagnosis. Anda hanya perlu tahu cara membuka kuncinya."
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Critical Question */}
      <section className="py-20 px-4 bg-gray-900">
        <div className="max-w-5xl mx-auto text-center space-y-8">
          <h2 className="text-4xl md:text-5xl font-bold">
            Pertanyaan yang Harus Anda Renungkan:
          </h2>

          <div className="grid md:grid-cols-3 gap-6 my-12">
            <div className="bg-red-900/30 border-2 border-red-500 rounded-xl p-6">
              <p className="text-6xl mb-4">💰</p>
              <p className="text-2xl font-bold text-red-300 mb-2">Puluhan Juta</p>
              <p className="text-gray-300">Anda habiskan untuk obat, rumah sakit, terapi...</p>
            </div>

            <div className="bg-red-900/30 border-2 border-red-500 rounded-xl p-6">
              <p className="text-6xl mb-4">😰</p>
              <p className="text-2xl font-bold text-red-300 mb-2">Stress & Takut</p>
              <p className="text-gray-300">Setiap hari hidup dalam ketidakpastian...</p>
            </div>

            <div className="bg-red-900/30 border-2 border-red-500 rounded-xl p-6">
              <p className="text-6xl mb-4">❓</p>
              <p className="text-2xl font-bold text-red-300 mb-2">Tidak Ada Hasil</p>
              <p className="text-gray-300">Kondisi stagnan atau bahkan memburuk...</p>
            </div>
          </div>

          <div className="bg-gradient-to-r from-yellow-900/50 to-orange-900/50 border-2 border-yellow-500 rounded-2xl p-8">
            <p className="text-3xl md:text-4xl font-bold text-yellow-400 mb-6">
              Tidak Maukah Anda Mengetahui Sesuatu yang DAHSYAT dengan Rp200.000?
            </p>
            <p className="text-2xl text-gray-200 leading-relaxed">
              Apakah <span className="text-red-400 font-bold">SESEPELE ITU</span> kesehatan Anda dan keluarga?
            </p>
          </div>
        </div>
      </section>

      {/* Solution - What You Get */}
      <section className="py-20 px-4 bg-black">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-6">
            Inilah Yang Mengubah Hidup Saya
          </h2>
          <p className="text-2xl text-center text-gray-300 mb-16">
            (Dan Bisa Mengubah Hidup Anda Juga)
          </p>

          <div className="bg-gradient-to-br from-gray-800 to-gray-900 border-2 border-green-500 rounded-2xl p-8 mb-12">
            <h3 className="text-3xl font-bold text-green-400 mb-6 flex items-center gap-3">
              <Sparkles className="w-8 h-8" /> EBOOK: "Rahasia Kesembuhan Natural"
            </h3>
            <p className="text-xl text-gray-200 leading-relaxed mb-6">
              Bukan teori semata. Ini adalah <span className="text-yellow-400 font-bold">SISTEM LENGKAP</span> yang saya gunakan untuk melawan vonis medis—dan MENANG.
            </p>
            <ul className="space-y-4 text-lg">
              <li className="flex items-start gap-3">
                <Check className="text-green-400 flex-shrink-0 mt-1" />
                <span>Metode <span className="font-bold">Kalibrasi Bio-Energetik</span> eL Vision yang terbukti</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-green-400 flex-shrink-0 mt-1" />
                <span>Protokol <span className="font-bold">Puasa Terapeutik</span> yang aman dan efektif</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-green-400 flex-shrink-0 mt-1" />
                <span>Teknik <span className="font-bold">Reset Pikiran Bawah Sadar</span> untuk penyembuhan</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-green-400 flex-shrink-0 mt-1" />
                <span>Panduan <span className="font-bold">Nutrisi & Detoksifikasi</span> step-by-step</span>
              </li>
            </ul>
            <div className="bg-green-900/20 border border-green-500/30 rounded-lg p-4 mt-6">
              <p className="text-green-300 font-bold">💎 NILAI: Rp2.500.000</p>
            </div>
          </div>

          <div className="bg-gradient-to-r from-purple-900/50 to-indigo-900/50 border-2 border-purple-500 rounded-2xl p-8 mb-12">
            <h3 className="text-3xl font-bold text-purple-400 mb-6 flex items-center gap-3">
              🎧 BONUS #1: Audio Hipnosis "REZEKI KESEHATAN"
            </h3>
            <p className="text-xl text-gray-200 leading-relaxed mb-4">
              Audio frekuensi khusus yang saya dengarkan setiap hari untuk <span className="text-yellow-400 font-bold">mengaktifkan sistem penyembuhan alami tubuh</span>.
            </p>
            <ul className="space-y-3 text-lg">
              <li className="flex items-start gap-3">
                <Check className="text-purple-400 flex-shrink-0 mt-1" />
                <span>Teknologi brainwave entrainment (gelombang Theta 4-7Hz)</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-purple-400 flex-shrink-0 mt-1" />
                <span>Durasi: 30 menit (pagi & malam)</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-purple-400 flex-shrink-0 mt-1" />
                <span>Reprogram pikiran bawah sadar untuk kesehatan optimal</span>
              </li>
            </ul>
            <div className="bg-purple-900/20 border border-purple-500/30 rounded-lg p-4 mt-6">
              <p className="text-purple-300 font-bold">💎 NILAI: Rp3.000.000</p>
            </div>
          </div>

          <div className="bg-gradient-to-r from-blue-900/50 to-cyan-900/50 border-2 border-blue-500 rounded-2xl p-8">
            <h3 className="text-3xl font-bold text-blue-400 mb-6 flex items-center gap-3">
              📱 BONUS #2: Panduan Beriklan Meta Ads
            </h3>
            <p className="text-xl text-gray-200 leading-relaxed mb-4">
              Jika Anda ingin membantu orang lain (seperti saya), ini panduan lengkap cara menjangkau mereka yang membutuhkan.
            </p>
            <ul className="space-y-3 text-lg">
              <li className="flex items-start gap-3">
                <Check className="text-blue-400 flex-shrink-0 mt-1" />
                <span>Setup kampanye Facebook & Instagram Ads dari nol</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-blue-400 flex-shrink-0 mt-1" />
                <span>Targeting untuk niche kesehatan & wellness</span>
              </li>
              <li className="flex items-start gap-3">
                <Check className="text-blue-400 flex-shrink-0 mt-1" />
                <span>Copy-paste template iklan yang proven convert</span>
              </li>
            </ul>
            <div className="bg-blue-900/20 border border-blue-500/30 rounded-lg p-4 mt-6">
              <p className="text-blue-300 font-bold">💎 NILAI: Rp1.500.000</p>
            </div>
          </div>

          <div className="bg-gradient-to-r from-yellow-600 to-orange-600 rounded-2xl p-8 mt-12 text-center">
            <p className="text-2xl mb-4">TOTAL NILAI PAKET INI:</p>
            <p className="text-5xl font-bold mb-2 line-through decoration-red-500 decoration-4">Rp7.000.000</p>
            <p className="text-3xl mb-4">HARGA HARI INI:</p>
            <p className="text-7xl font-bold text-white">Rp200.000</p>
            <p className="text-2xl mt-4 font-bold">HEMAT 97% 🔥</p>
          </div>
        </div>
      </section>

      {/* Guarantee */}
      <section className="py-20 px-4 bg-gray-900">
        <div className="max-w-4xl mx-auto text-center">
          <Shield className="w-20 h-20 text-green-400 mx-auto mb-6" />
          <h2 className="text-4xl md:text-5xl font-bold mb-8">
            100% GARANSI UANG KEMBALI
          </h2>
          <div className="bg-gradient-to-r from-green-900/50 to-emerald-900/50 border-2 border-green-500 rounded-2xl p-8">
            <p className="text-2xl text-gray-200 leading-relaxed mb-6">
              Jika setelah membaca ebook dan mendengarkan audio ini Anda merasa <span className="text-red-400 font-bold">TIDAK MANFAAT SAMA SEKALI</span>, hubungi saya dalam 30 hari—
            </p>
            <p className="text-3xl font-bold text-green-400">
              UANG ANDA KEMBALI 100%, TANPA PERTANYAAN.
            </p>
            <p className="text-xl text-gray-300 mt-6 italic">
              Karena saya tahu betapa berharganya uang Anda. Dan saya tidak ingin mengambil sepeser pun jika ini tidak membantu.
            </p>
          </div>
        </div>
      </section>

      {/* Final Push */}
      <section className="py-20 px-4 bg-black">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-12">
            Dua Pilihan di Hadapan Anda
          </h2>

          <div className="grid md:grid-cols-2 gap-8 mb-16">
            <div className="bg-gradient-to-br from-red-900/50 to-black border-4 border-red-500 rounded-xl p-8">
              <X className="w-16 h-16 text-red-400 mx-auto mb-6" />
              <h3 className="text-2xl font-bold text-red-400 mb-6 text-center">PILIHAN #1: Tidak Berbuat Apa-Apa</h3>
              <ul className="space-y-4 text-lg">
                <li className="flex items-start gap-3">
                  <X className="text-red-400 flex-shrink-0 mt-1" />
                  <span>Terus menghabiskan puluhan juta tanpa hasil</span>
                </li>
                <li className="flex items-start gap-3">
                  <X className="text-red-400 flex-shrink-0 mt-1" />
                  <span>Hidup dalam ketakutan & ketidakpastian</span>
                </li>
                <li className="flex items-start gap-3">
                  <X className="text-red-400 flex-shrink-0 mt-1" />
                  <span>Kondisi kesehatan stagnan atau memburuk</span>
                </li>
                <li className="flex items-start gap-3">
                  <X className="text-red-400 flex-shrink-0 mt-1" />
                  <span>Menyesal di kemudian hari: "Seandainya saya coba..."</span>
                </li>
              </ul>
            </div>

            <div className="bg-gradient-to-br from-green-900/50 to-emerald-900/50 border-4 border-green-500 rounded-xl p-8">
              <Check className="w-16 h-16 text-green-400 mx-auto mb-6" />
              <h3 className="text-2xl font-bold text-green-400 mb-6 text-center">PILIHAN #2: Investasi Rp200.000</h3>
              <ul className="space-y-4 text-lg">
                <li className="flex items-start gap-3">
                  <Check className="text-green-400 flex-shrink-0 mt-1" />
                  <span>Akses sistem yang TERBUKTI bekerja</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="text-green-400 flex-shrink-0 mt-1" />
                  <span>Mulai perjalanan penyembuhan HARI INI</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="text-green-400 flex-shrink-0 mt-1" />
                  <span>Harapan baru untuk Anda & keluarga</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="text-green-400 flex-shrink-0 mt-1" />
                  <span>100% garansi—ZERO RISIKO</span>
                </li>
              </ul>
            </div>
          </div>

          <div className="bg-gradient-to-r from-yellow-900/50 to-orange-900/50 border-2 border-yellow-500 rounded-2xl p-8 text-center">
            <p className="text-3xl font-bold text-yellow-400 mb-4">
              Rp200.000 vs Puluhan Juta yang Sudah Anda Keluarkan
            </p>
            <p className="text-2xl text-gray-200 leading-relaxed">
              Manakah yang lebih masuk akal untuk DICOBA?
            </p>
          </div>
        </div>
      </section>

      {/* Personal Message */}
      <section className="py-20 px-4 bg-black">
        <div className="max-w-3xl mx-auto">
          <div className="bg-gradient-to-r from-gray-800 to-gray-900 border-2 border-yellow-500 rounded-2xl p-10">
            <Heart className="w-16 h-16 text-red-500 mx-auto mb-6" />
            <h3 className="text-3xl font-bold text-yellow-400 mb-6 text-center">Pesan Terakhir dari Saya</h3>
            <div className="space-y-4 text-lg text-gray-200 leading-relaxed">
              <p>
                Saya tidak akan berbohong kepada Anda. Saya Ingin membuka mata anda bahwa pengetahuan saat ini terbatas dan kekuatan kedamaian ini bekerja.
              </p>
              <p>
                Tapi lebih dari itu, <span className="text-yellow-400 font-bold">saya ingin memberikan harapan</span>—seperti yang diberikan kepada saya.
              </p>
              <p>
                Jika Anda atau orang yang Anda cintai sedang berjuang melawan penyakit, jangan menyerah. <span className="text-green-400 font-bold">Ada jalan keluar yang mungkin belum Anda ketahui.</span>
              </p>
              <p className="text-2xl font-bold text-center text-green-400 mt-8">
                Rp200.000 bisa menjadi investasi terbaik untuk kesehatan Anda.
              </p>
              <p className="text-center italic mt-4">
                Saya doakan Anda segera pulih dan sehat kembali. 🤲
              </p>
              <p className="text-right font-bold text-yellow-400 mt-6">
                — Syarifudin Arif
              </p>
            </div>
            <a
              href="https://app.elvisiongroup.com/testimony"
              target="_blank"
              rel="noopener noreferrer"
              className="mt-8 w-full inline-flex items-center justify-center gap-2 bg-gradient-to-r from-blue-500 to-indigo-600 text-white text-xl font-bold py-4 px-8 rounded-full hover:from-blue-600 hover:to-indigo-700 transition-all transform hover:scale-105 shadow-xl"
            >
              Testimony dan Cara Kerja <ArrowRight className="w-5 h-5" />
            </a>
          </div>
        </div>
      </section>

      {/* Additional Video Section - Before FAQ */}
      <section className="py-10 px-4 bg-black">
        <div className="max-w-4xl mx-auto">
          <div className="bg-gradient-to-br from-gray-900 to-black border-2 border-green-500/50 rounded-2xl p-8 shadow-2xl">
            <h3 className="text-2xl font-bold text-center mb-6 text-green-400">
              Perjalanan Kesembuhan Saya (Bagian 1)
            </h3>
            <div className="max-w-sm mx-auto">
              <video 
                className="w-full rounded-lg shadow-xl border border-gray-800"
                controls
                preload="metadata"
                playsInline
                webkit-playsinline="true"
                poster="https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/arifweb/arif1.jpeg"
              >
                <source src="https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/arifweb/arif1.mp4" type="video/mp4" />
                Browser Anda tidak mendukung pemutaran video.
              </video>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ SECTION */}
      <section className="py-16 px-6 bg-gray-900">
        <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-bold text-center mb-10 text-white">Pertanyaan Yang Sering Diajukan</h2>
            <div className="space-y-4">
                <div className="bg-gray-800 px-4 py-4 rounded-lg border border-gray-700">
                    <h3 className="text-white font-semibold mb-2">Berapa lama sampai terlihat hasilnya?</h3>
                    <p className="text-gray-400">
                        Sebagian besar pengguna merasakan perubahan mental (lebih tenang & damai) dalam 3-7 hari pertama. Perubahan kesehatan fisik biasanya terjadi setelah 21 hari rutin mendengarkan.
                    </p>
                </div>
                <div className="bg-gray-800 px-4 py-4 rounded-lg border border-gray-700">
                    <h3 className="text-white font-semibold mb-2">Apakah ini hipnotis? Apakah aman?</h3>
                    <p className="text-gray-400">
                        Ini adalah terapi frekuensi gelombang otak (brainwave entrainment) yang dikombinasikan dengan sugesti positif, bukan hipnotis panggung. Anda tetap sadar dan memiliki kontrol penuh. Audio ini hanya membantu Anda masuk ke gelombang otak rileks (Theta) untuk mengaktifkan sistem penyembuhan alami tubuh. 100% Aman.
                    </p>
                </div>
                <div className="bg-gray-800 px-4 py-4 rounded-lg border border-gray-700">
                    <h3 className="text-white font-semibold mb-2">Bisa didengar sambil kerja atau menyetir?</h3>
                    <p className="text-red-400 font-bold">
                        TIDAK BOLEH. Audio ini menyebabkan kantuk dan relaksasi dalam. Hanya dengarkan saat Anda dalam posisi istirahat atau sebelum tidur.
                    </p>
                </div>
                <div className="bg-gray-800 px-4 py-4 rounded-lg border border-gray-700">
                    <h3 className="text-white font-semibold mb-2">Saya gaptek, cara pakainya gimana?</h3>
                    <p className="text-gray-400">
                        Sangat mudah. Setelah bayar, link download dikirim ke email. Tinggal klik, download ke HP, dan putar pakai earphone. Ada panduan lengkapnya juga di dalam.
                    </p>
                </div>
            </div>
        </div>
      </section>

      {/* Checkout Section */}
      <section id="checkout" className="py-20 px-4 bg-gray-900">
        <div className="max-w-2xl mx-auto">
          <div className="bg-gradient-to-br from-gray-800 to-black border-2 border-green-500 rounded-2xl overflow-hidden shadow-2xl">
            <div className="bg-gradient-to-r from-red-600 to-orange-600 p-4 text-center">
              <p className="font-bold text-lg">⏰ PROMO BERAKHIR: {timeLeft.hours}:{String(timeLeft.minutes).padStart(2,'0')}:{String(timeLeft.seconds).padStart(2,'0')}</p>
            </div>

            <div className="p-8 space-y-8">
              <div className="text-center">
                <h3 className="text-3xl font-bold mb-4">FORMULIR PEMESANAN</h3>
                <div className="bg-green-900/30 border-2 border-green-500 rounded-xl p-6">
                  <p className="text-gray-400 mb-2">Investasi Anda Hari Ini:</p>
                  <p className="text-5xl font-bold text-green-400">Rp200.000</p>
                  <p className="text-sm text-gray-400 mt-2">✅ Akses Selamanya • Garansi 30 Hari</p>
                </div>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="block text-gray-300 font-semibold mb-2">Nama Lengkap</label>
                  <input
                    type="text"
                    placeholder="Nama Anda"
                    value={userName}
                    onChange={(e) => setUserName(e.target.value)}
                    className="w-full bg-gray-700 border-2 border-gray-600 rounded-lg px-4 py-3 text-white focus:border-green-500 focus:outline-none"
                  />
                </div>

                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-gray-300 font-semibold mb-2">Email</label>
                    <input
                      type="email"
                      placeholder="email@anda.com"
                      value={userEmail}
                      onChange={(e) => setUserEmail(e.target.value)}
                      className="w-full bg-gray-700 border-2 border-gray-600 rounded-lg px-4 py-3 text-white focus:border-green-500 focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-gray-300 font-semibold mb-2">WhatsApp</label>
                    <input
                      type="tel"
                      placeholder="0812..."
                      value={phoneNumber}
                      onChange={(e) => setPhoneNumber(e.target.value)}
                      className="w-full bg-gray-700 border-2 border-gray-600 rounded-lg px-4 py-3 text-white focus:border-green-500 focus:outline-none"
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <label className="block text-gray-300 font-semibold mb-3">Metode Pembayaran</label>
                {paymentMethods.map((method) => (
                  <label
                    key={method.code}
                    className={`flex items-center p-4 border-2 rounded-lg cursor-pointer transition-all ${
                      selectedPaymentMethod === method.code
                        ? 'border-green-500 bg-green-900/20'
                        : 'border-gray-700 bg-gray-800 hover:border-gray-600'
                    }`}
                  >
                    <input
                      type="radio"
                      name="payment"
                      value={method.code}
                      checked={selectedPaymentMethod === method.code}
                      onChange={(e) => setSelectedPaymentMethod(e.target.value)}
                      className="mr-4"
                    />
                    <div>
                      <div className="font-bold text-white">{method.name}</div>
                      <div className="text-sm text-gray-400">{method.description}</div>
                    </div>
                  </label>
                ))}
              </div>

              <button
                onClick={handleCreatePayment}
                disabled={loading}
                className="w-full bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white text-2xl font-bold py-6 rounded-full transition-all transform hover:scale-105 shadow-2xl"
              >
                {loading ? 'Memproses...' : `🔥 BELI SEKARANG - ${formatCurrency(totalAmount)}`}
              </button>

              <p className="text-center text-gray-400 text-sm">
                🔒 Pembayaran 100% Aman • ⚡ Akses Instant
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default ArifEbookLanding;