import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface CreatePaymentRequest {
  subscriptionType: 'monthly' | 'yearly';
  paymentMethod: string;
  userEmail: string;
  userName: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get the authorization header to identify the user
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      throw new Error('No authorization header')
    }

    // Create Supabase client with service role for admin operations
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Get the user from the auth header
    const token = authHeader.replace('Bearer ', '')
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser(token)
    
    if (userError || !user) {
      throw new Error('Invalid authentication')
    }

    // Parse the request body
    const { subscriptionType, paymentMethod, userEmail, userName }: CreatePaymentRequest = await req.json()

    if (!subscriptionType || !paymentMethod || !userEmail) {
      throw new Error('Missing required parameters')
    }

    console.log('Creating payment for user:', user.id, 'subscription:', subscriptionType, 'method:', paymentMethod)

    // Calculate amounts based on subscription type
    const amounts = {
      monthly: 50000, // 50k IDR per month
      yearly: 500000  // 500k IDR per year (save 100k)
    }
    
    const amount = amounts[subscriptionType]
    if (!amount) {
      throw new Error('Invalid subscription type')
    }

    // Generate unique merchant reference
    const merchantRef = `ELV_${Date.now()}_${user.id.substring(0, 8)}`
    
    // Create or get VIP subscription record
    const { data: existingSubscription } = await supabaseClient
      .from('vip_subscriptions')
      .select('id')
      .eq('user_id', user.id)
      .maybeSingle()

    let subscriptionId: string

    if (existingSubscription) {
      subscriptionId = existingSubscription.id
      // Update existing subscription
      await supabaseClient
        .from('vip_subscriptions')
        .update({
          subscription_type: subscriptionType,
          status: 'pending',
          updated_at: new Date().toISOString()
        })
        .eq('user_id', user.id)
    } else {
      // Create new subscription
      const { data: newSubscription, error: subError } = await supabaseClient
        .from('vip_subscriptions')
        .insert({
          user_id: user.id,
          subscription_type: subscriptionType,
          status: 'pending'
        })
        .select('id')
        .single()

      if (subError || !newSubscription) {
        throw new Error('Failed to create subscription record')
      }
      
      subscriptionId = newSubscription.id
    }

    // Prepare data for the VPS proxy
    const proxyPayload = {
      merchant_ref: merchantRef,
      amount: amount,
      customer_name: userName || userEmail.split('@')[0],
      customer_email: userEmail,
      customer_phone: '', // Optional
      order_items: [
        {
          sku: `ELVISION_${subscriptionType.toUpperCase()}`,
          name: `eL Vision Group - ${subscriptionType === 'monthly' ? 'Monthly' : 'Yearly'} Subscription`,
          price: amount,
          quantity: 1,
          product_url: 'https://elvisiongroup.com',
          image_url: 'https://elvisiongroup.com/logo.png'
        }
      ],
      return_url: `${req.headers.get('origin') || 'https://elvisiongroup.com'}/profile`,
      expired_time: (Math.floor(Date.now() / 1000) + (24 * 60 * 60)), // 24 hours from now
      signature: '', // Will be generated by proxy
      method: paymentMethod,
      subscription_type: subscriptionType,
      user_id: user.id
    }

    console.log('Sending request to VPS proxy:', proxyPayload)

    // Call the VPS proxy to create Tripay payment
    const vpsProxyUrl = 'https://payment.elvisiongroup.com/create-payment'
    const tripayResponse = await fetch(vpsProxyUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-proxy-key': Deno.env.get("PROXY_API_KEY") ?? ""
      },
      body: JSON.stringify(proxyPayload)
    })

    if (!tripayResponse.ok) {
      const errorText = await tripayResponse.text()
      console.error('VPS proxy error:', errorText)
      throw new Error(`Payment gateway error: ${tripayResponse.status}`)
    }

    const tripayData = await tripayResponse.json()
    console.log('Tripay response received:', tripayData)

    // Store payment transaction
    const { data: transaction, error: transactionError } = await supabaseClient
      .from('payment_transactions')
      .insert({
        user_id: user.id,
        subscription_id: subscriptionId,
        tripay_reference: tripayData.data?.reference || merchantRef,
        tripay_merchant_ref: merchantRef,
        payment_method: paymentMethod,
        amount: amount,
        currency: 'IDR',
        status: 'pending',
        payment_url: tripayData.data?.checkout_url,
        payment_instructions: tripayData.data?.instructions || {},
        callback_data: {
          tripay_data: tripayData.data,
          subscription_type: subscriptionType
        },
        expires_at: new Date(Date.now() + (24 * 60 * 60 * 1000)).toISOString() // 24 hours
      })
      .select('*')
      .single()

    if (transactionError) {
      console.error('Transaction creation error:', transactionError)
      throw new Error('Failed to store payment transaction')
    }

    console.log('Payment transaction created:', transaction.id)

    // Store the payment in tripay-store-payment function
    try {
      const { error: storeError } = await supabaseClient.functions.invoke('tripay-store-payment', {
        body: {
          subscription_type: subscriptionType,
          tripay_data: tripayData.data,
          user_id: user.id,
          transaction_id: transaction.id
        }
      })

      if (storeError) {
        console.error('Store payment error:', storeError)
      }
    } catch (storeErr) {
      console.error('Failed to call store payment function:', storeErr)
      // Don't throw here, payment creation was successful
    }

    // Return success response
    return new Response(
      JSON.stringify({
        success: true,
        message: 'Payment created successfully',
        data: {
          reference: tripayData.data?.reference || merchantRef,
          checkout_url: tripayData.data?.checkout_url,
          amount: amount,
          currency: 'IDR',
          expires_at: transaction.expires_at,
          payment_method: paymentMethod,
          instructions: tripayData.data?.instructions
        }
      }),
      {
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        },
        status: 200
      }
    )

  } catch (error) {
    console.error('Tripay create payment error:', error)
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message || 'Payment creation failed',
        message: 'Failed to create payment. Please try again.'
      }),
      {
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        },
        status: 400
      }
    )
  }
})